In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
df = pd.read_csv('/content/10_Iris.csv')

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [ ]:
setosa = df[df['Species']=='Iris-setosa']
versicolor = df[df['Species']=='Iris-versicolor']
virginica = df[df['Species']=='Iris-virginica']

In [ ]:
v_species = pd.concat([versicolor , virginica] , axis =0)

In [ ]:
v_species

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
sort_v = v_species.sort_values(by = 'PetalLengthCm' , ascending  = True)
sort_v

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
...,...,...,...,...,...,...
131,132,7.9,3.8,6.4,2.0,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica

In [ ]:
transpose = sort_v.transpose()

In [ ]:
transpose

,98,57,93,79,60,64,81,80,69,82,...,100,135,109,130,107,131,105,117,122,118
Id,99,58,94,80,61,65,82,81,70,83,...,101,136,110,131,108,132,106,118,123,119
SepalLengthCm,5.1,4.9,5.0,5.7,5.0,5.6,5.5,5.5,5.6,5.8,...,6.3,7.7,7.2,7.4,7.3,7.9,7.6,7.7,7.7,7.7
SepalWidthCm,2.5,2.4,2.3,2.6,2.0,2.9,2.4,2.4,2.5,2.7,...,3.3,3.0,3.6,2.8,2.9,3.8,3.0,3.8,2.8,2.6
PetalLengthCm,3.0,3.3,3.3,3.5,3.5,3.6,3.7,3.8,3.9,3.9,...,6.0,6.1,6.1,6.1,6.3,6.4,6.6,6.7,6.7,6.9
PetalWidthCm,1.1,1.0,1.0,1.0,1.0,1.3,1.0,1.1,1.1,1.2,...,2.5,2.3,2.5,1.9,1.8,2.0,2.1,2.2,2.0,2.3
Species,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-versicolor,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [ ]:
sort_v = sort_v.drop(['Id'] , axis = 1)
melt = sort_v.melt(id_vars=['Species'] , var_name='Dimension' , value_name = 'Length & Width')

In [ ]:
melt

             Species      Dimension  Length & Width
0    Iris-versicolor  SepalLengthCm             5.1
1    Iris-versicolor  SepalLengthCm             4.9
2    Iris-versicolor  SepalLengthCm             5.0
3    Iris-versicolor  SepalLengthCm             5.7
4    Iris-versicolor  SepalLengthCm             5.0
..               ...            ...             ...
395   Iris-virginica   PetalWidthCm             2.0
396   Iris-virginica   PetalWidthCm             2.1
397   Iris-virginica   PetalWidthCm             2.2
398   Iris-virginica   PetalWidthCm             2.0
399   Iris-virginica   PetalWidthCm             2.3

[400 rows x 3 columns]

In [ ]:
cast = pd.pivot_table(sort_v , index = ['Species'  ])
cast

                 PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
Species
Iris-versicolor          4.260         1.326          5.936         2.770
Iris-virginica           5.552         2.026          6.588         2.974